spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/yapily-template-db
    username: local
    password: local


jose-batch:
  chunk-size: 100
  page-size: 10
  table: yapily_user
  id: id
  fields:
    - name

jose-database:
  keys-path: file:/tmp/keys/
  encryption-method: A128CBC-HS256
  token-format: JWS_JWE